spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IHQ # URL de conexão ao banco de dados PostgreSQL
    username: admin # Nome de usuário do banco de dados
    password: admin # Senha do banco de dados
    driver-class-name: org.postgresql.Driver # Driver JDBC do PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update # Atualiza automaticamente o esquema do banco de dados
    show-sql: false # Desativa a exibição das instruções SQL no console
    properties:
      hibernate:
        format_sql: true # Formata o SQL gerado para facilitar a leitura
    database: postgresql # Especifica que o banco de dados utilizado é o PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Chave secreta para assinatura JWT
      expiration: 86400000 # Tempo de expiração do token JWT (em milissegundos, aqui é 1 dia)
      refresh-token:
        expiration: 604800000 # Tempo de expiração do refresh token (em milissegundos, aqui é 7 dias)
